"""ORM model package.

Importing this package imports every model, which registers all tables on
``Base.metadata`` -- exactly what Alembic's autogenerate and the seed script
need.
"""

from __future__ import annotations

from .catalog_groups import CatalogGroup
from .custom_tables import CatalogColumnDef, CatalogCustomRow
from .catalogs import (
    CatalogCable,
    CatalogDevice,
    CatalogEquipment,
    CatalogInstrument,
    CatalogIOModule,
    CatalogManufacturer,
)
from .catalogs_ext import (
    ALL_EXT_CATALOGS,
    AreaTypeCatalog,
    ATSCatalog,
    BreakerCatalog,
    CableInsulationCatalog,
    CableTrayCatalog,
    CommunicationProtocolCatalog,
    ConductorMaterialCatalog,
    ConduitRoutingCatalog,
    ConduitTypeCatalog,
    DisconnectSwitchCatalog,
    DocumentTypeCatalog,
    DrawingTypeCatalog,
    EnclosureCatalog,
    EnvironmentalRatingCatalog,
    EquipmentModelCatalog,
    EquipmentTypeCatalog,
    FuseCatalog,
    GeneratorCatalog,
    GroundingTypeCatalog,
    HazardousAreaCatalog,
    InstallationMethodCatalog,
    InstrumentModelCatalog,
    MCCCatalog,
    MeasurementTypeCatalog,
    MountingDetailCatalog,
    MountingTypeCatalog,
    NetworkDeviceCatalog,
    OverloadCatalog,
    PanelboardCatalog,
    PhaseWireConfigCatalog,
    PLCCatalog,
    PLCIOCatalog,
    PowerSystemCatalog,
    ProcessConnectionCatalog,
    RelayCatalog,
    RevisionStatusCatalog,
    RoomTypeCatalog,
    SCADACatalog,
    SignalTypeCatalog,
    SoftStarterCatalog,
    SubmittalStatusCatalog,
    SwitchboardCatalog,
    SwitchgearCatalog,
    TerminationTypeCatalog,
    TransformerCatalog,
    UPSCatalog,
    VFDCatalog,
    VoltageClassCatalog,
    WireTypeCatalog,
)
from .enums import (
    AlarmPriority,
    CableEnd,
    CalcStatus,
    CalcType,
    ConductorMaterial,
    ConduitMaterial,
    ConduitType,
    DeviceCategory,
    DrawingStatus,
    DrawingType,
    EquipmentCategory,
    IndoorOutdoor,
    InstrumentType,
    IOType,
    IssueStage,
    NetworkDeviceType,
    NetworkProtocol,
    ProjectStatus,
    QAQCCategory,
    QAQCSeverity,
    QAQCStatus,
    RouteType,
    TerminationType,
    UL508AStatus,
)
from .pipeline import ProjectPipelineProgress
from .projects import (
    Project,
    ProjectCable,
    ProjectCableRoute,
    ProjectCalculation,
    ProjectConduit,
    ProjectControlPanel,
    ProjectDrawing,
    ProjectEquipment,
    ProjectFeeder,
    ProjectInstrument,
    ProjectIOPoint,
    ProjectLocation,
    ProjectNetworkDevice,
    ProjectPanelCircuit,
    ProjectPanelComponent,
    ProjectQAQCCheck,
    ProjectTerminalBlock,
    ProjectTermination,
)

__all__ = [
    # Catalog hierarchy
    "CatalogGroup",
    # Custom table schema
    "CatalogColumnDef",
    "CatalogCustomRow",
    # Class A -- core catalogs
    "CatalogManufacturer",
    "CatalogEquipment",
    "CatalogCable",
    "CatalogInstrument",
    "CatalogIOModule",
    "CatalogDevice",
    # Class A -- extended catalogs (Groups 1-10)
    "ALL_EXT_CATALOGS",
    "PowerSystemCatalog",
    "VoltageClassCatalog",
    "GroundingTypeCatalog",
    "PhaseWireConfigCatalog",
    "EquipmentTypeCatalog",
    "EquipmentModelCatalog",
    "EnclosureCatalog",
    "MountingTypeCatalog",
    "SwitchgearCatalog",
    "SwitchboardCatalog",
    "MCCCatalog",
    "PanelboardCatalog",
    "TransformerCatalog",
    "ATSCatalog",
    "GeneratorCatalog",
    "UPSCatalog",
    "BreakerCatalog",
    "FuseCatalog",
    "RelayCatalog",
    "OverloadCatalog",
    "DisconnectSwitchCatalog",
    "SoftStarterCatalog",
    "VFDCatalog",
    "ConduitTypeCatalog",
    "CableTrayCatalog",
    "WireTypeCatalog",
    "CableInsulationCatalog",
    "ConductorMaterialCatalog",
    "InstrumentModelCatalog",
    "SignalTypeCatalog",
    "MeasurementTypeCatalog",
    "ProcessConnectionCatalog",
    "PLCCatalog",
    "PLCIOCatalog",
    "SCADACatalog",
    "NetworkDeviceCatalog",
    "CommunicationProtocolCatalog",
    "AreaTypeCatalog",
    "RoomTypeCatalog",
    "HazardousAreaCatalog",
    "EnvironmentalRatingCatalog",
    "DrawingTypeCatalog",
    "RevisionStatusCatalog",
    "DocumentTypeCatalog",
    "SubmittalStatusCatalog",
    "InstallationMethodCatalog",
    "MountingDetailCatalog",
    "ConduitRoutingCatalog",
    "TerminationTypeCatalog",
    # Class B -- project tables
    "Project",
    "ProjectLocation",
    "ProjectEquipment",
    "ProjectFeeder",
    "ProjectPanelCircuit",
    "ProjectCable",
    "ProjectCableRoute",
    "ProjectConduit",
    "ProjectInstrument",
    "ProjectIOPoint",
    "ProjectControlPanel",
    "ProjectPanelComponent",
    "ProjectTerminalBlock",
    "ProjectTermination",
    "ProjectNetworkDevice",
    "ProjectDrawing",
    "ProjectCalculation",
    "ProjectQAQCCheck",
    # pipeline
    "ProjectPipelineProgress",
    # enums
    "AlarmPriority",
    "CableEnd",
    "CalcStatus",
    "CalcType",
    "ConductorMaterial",
    "ConduitMaterial",
    "ConduitType",
    "DeviceCategory",
    "DrawingStatus",
    "DrawingType",
    "EquipmentCategory",
    "IndoorOutdoor",
    "InstrumentType",
    "IOType",
    "IssueStage",
    "NetworkDeviceType",
    "NetworkProtocol",
    "ProjectStatus",
    "QAQCCategory",
    "QAQCSeverity",
    "QAQCStatus",
    "RouteType",
    "TerminationType",
    "UL508AStatus",
]
