"""Shared schema building blocks.

Every table follows the same pattern:

* ``XCreate``  -- the editable fields, with correct required/optional flags.
* ``XRead``    -- ``XCreate`` plus ``id`` and the timestamp columns.
* ``XUpdate``  -- a *partial* schema where every field is optional, generated by
  :func:`make_optional` so a PUT can carry just the changed fields.
* ``XMerged``  -- (Class B catalog-linked tables only) ``XRead`` plus the nested
  catalog record, i.e. the merged representation the UI displays.

Keeping that pattern in one place avoids dozens of near-identical classes.
"""

from __future__ import annotations

from typing import Generic, TypeVar

from pydantic import BaseModel, ConfigDict, create_model

T = TypeVar("T")


class ORMModel(BaseModel):
    """Base for every schema; reads attributes straight off ORM objects."""

    model_config = ConfigDict(from_attributes=True)


class ListResponse(BaseModel, Generic[T]):
    """Envelope for paginated list endpoints."""

    items: list[T]
    total: int  # total rows matching the filter, ignoring pagination
    skip: int
    limit: int


def make_optional(base: type[BaseModel], name: str) -> type[BaseModel]:
    """Return a copy of ``base`` with every field made optional (default None).

    Used to derive the ``*Update`` schemas.  A PUT then only needs to send the
    fields that actually change; untouched fields are left as-is by the endpoint
    (which applies the body with ``exclude_unset=True``).

    Note: validators on ``base`` are intentionally *not* carried over -- the
    cross-field "catalog reference OR custom data" rule cannot be checked on a
    partial body, so it is enforced by the database CHECK constraint instead.
    """
    fields = {
        field_name: (field_info.annotation | None, None)
        for field_name, field_info in base.model_fields.items()
    }
    return create_model(name, __base__=ORMModel, **fields)  # type: ignore[call-overload]
