"""expand schema: new fields and 9 project tables

Revision ID: 0db355f1563c
Revises: 3d1c278b0f52
Create Date: 2026-05-22 17:09:24.711601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db355f1563c'
down_revision: Union[str, None] = '3d1c278b0f52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_calculations',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('calc_number', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('calc_type', sa.Enum('LOAD', 'VOLTAGE_DROP', 'SHORT_CIRCUIT', 'CONDUIT_FILL', 'GROUNDING', 'LIGHTING', 'CABLE_AMPACITY', 'ARC_FLASH', 'OTHER', name='calctype', native_enum=False), nullable=True),
    sa.Column('revision', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PRELIMINARY', 'IN_PROGRESS', 'COMPLETE', 'CHECKED', 'APPROVED', 'OTHER', name='calcstatus', native_enum=False), nullable=True),
    sa.Column('result_summary', sa.String(length=200), nullable=True),
    sa.Column('performed_by', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'calc_number', name='uq_project_calc_number')
    )
    op.create_table('project_drawings',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('drawing_number', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('drawing_type', sa.Enum('ONE_LINE', 'SCHEMATIC', 'PANEL_LAYOUT', 'LOOP_DIAGRAM', 'PID', 'LOCATION_PLAN', 'CABLE_ROUTING', 'DETAIL', 'OTHER', name='drawingtype', native_enum=False), nullable=True),
    sa.Column('revision', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PRELIMINARY', 'IFR', 'IFA', 'IFB', 'IFC', 'AS_BUILT', 'OTHER', name='drawingstatus', native_enum=False), nullable=True),
    sa.Column('discipline', sa.String(length=60), nullable=True),
    sa.Column('sheet_size', sa.String(length=20), nullable=True),
    sa.Column('scale', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'drawing_number', name='uq_project_drawing_number')
    )
    op.create_table('project_feeders',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('feeder_tag', sa.String(length=60), nullable=False),
    sa.Column('source_equipment_id', sa.Integer(), nullable=True),
    sa.Column('load_equipment_id', sa.Integer(), nullable=True),
    sa.Column('voltage', sa.String(length=40), nullable=True),
    sa.Column('phases', sa.String(length=20), nullable=True),
    sa.Column('ampacity', sa.String(length=40), nullable=True),
    sa.Column('ocpd_type', sa.String(length=60), nullable=True),
    sa.Column('ocpd_rating', sa.String(length=40), nullable=True),
    sa.Column('feeder_cable_id', sa.Integer(), nullable=True),
    sa.Column('drawing_reference', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['feeder_cable_id'], ['project_cables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['load_equipment_id'], ['project_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_equipment_id'], ['project_equipment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'feeder_tag', name='uq_project_feeder_tag')
    )
    op.create_table('project_qaqc_checks',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('check_item', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('TAGGING', 'POWER', 'CABLES', 'INSTRUMENTS', 'IO', 'TERMINATIONS', 'DRAWINGS', 'GENERAL', 'OTHER', name='qaqccategory', native_enum=False), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='qaqcseverity', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PASS', 'FAIL', 'NOT_APPLICABLE', 'RESOLVED', name='qaqcstatus', native_enum=False), nullable=False),
    sa.Column('related_reference', sa.String(length=120), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('checked_by', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_cable_routes',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('route_tag', sa.String(length=60), nullable=False),
    sa.Column('route_type', sa.Enum('TRAY', 'CONDUIT', 'DUCTBANK', 'DIRECT_BURIED', 'FREE_AIR', 'OTHER', name='routetype', native_enum=False), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('total_length', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'route_tag', name='uq_project_cable_route_tag')
    )
    op.create_table('project_conduits',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('conduit_tag', sa.String(length=60), nullable=False),
    sa.Column('conduit_type', sa.Enum('CONDUIT', 'CABLE_TRAY', 'DUCTBANK', 'WIREWAY', name='conduittype', native_enum=False), nullable=True),
    sa.Column('trade_size', sa.String(length=40), nullable=True),
    sa.Column('material', sa.Enum('PVC', 'RMC', 'EMT', 'IMC', 'ALUMINUM', 'GALV_STEEL', 'FIBERGLASS', 'OTHER', name='conduitmaterial', native_enum=False), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('fill_percent', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['project_cable_routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'conduit_tag', name='uq_project_conduit_tag')
    )
    op.create_table('project_network_devices',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('device_tag', sa.String(length=60), nullable=False),
    sa.Column('device_type', sa.Enum('SWITCH', 'ROUTER', 'GATEWAY', 'FIREWALL', 'ACCESS_POINT', 'MEDIA_CONVERTER', 'OTHER', name='networkdevicetype', native_enum=False), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('subnet_mask', sa.String(length=45), nullable=True),
    sa.Column('protocol', sa.Enum('ETHERNET_IP', 'MODBUS_TCP', 'PROFINET', 'OPC_UA', 'DNP3', 'BACNET', 'OTHER', name='networkprotocol', native_enum=False), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('control_panel_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['control_panel_id'], ['project_control_panels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'device_tag', name='uq_project_network_device_tag')
    )
    op.create_table('project_terminal_blocks',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('control_panel_id', sa.Integer(), nullable=True),
    sa.Column('terminal_strip', sa.String(length=40), nullable=False),
    sa.Column('terminal_number', sa.String(length=20), nullable=False),
    sa.Column('wire_number', sa.String(length=40), nullable=True),
    sa.Column('cable_id', sa.Integer(), nullable=True),
    sa.Column('conductor_core', sa.String(length=40), nullable=True),
    sa.Column('device_tag', sa.String(length=60), nullable=True),
    sa.Column('signal_description', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cable_id'], ['project_cables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['control_panel_id'], ['project_control_panels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_terminations',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cable_id', sa.Integer(), nullable=False),
    sa.Column('cable_end', sa.Enum('FROM', 'TO', name='cableend', native_enum=False), nullable=True),
    sa.Column('conductor_core', sa.String(length=40), nullable=True),
    sa.Column('termination_type', sa.Enum('LUG', 'RING', 'FERRULE', 'TERMINAL_BLOCK', 'SPLICE', 'DIRECT', 'OTHER', name='terminationtype', native_enum=False), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('terminal_block_id', sa.Integer(), nullable=True),
    sa.Column('device_tag', sa.String(length=60), nullable=True),
    sa.Column('drawing_reference', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cable_id'], ['project_cables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['project_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['terminal_block_id'], ['project_terminal_blocks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_cables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drawing_reference', sa.String(length=80), nullable=True))
        batch_op.create_foreign_key('fk_project_cables_route_id', 'project_cable_routes', ['route_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('project_control_panels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panel_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('voltage', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('enclosure_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('sccr', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('ul508a_status', sa.Enum('LISTED', 'NOT_LISTED', 'PENDING', 'NOT_APPLICABLE', name='ul508astatus', native_enum=False), nullable=True))

    with op.batch_alter_table('project_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('voltage', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('phase', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hp_kw', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('fla', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('feeder_cable_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drawing_reference', sa.String(length=80), nullable=True))
        batch_op.create_foreign_key('fk_project_equipment_feeder_cable_id', 'project_cables', ['feeder_cable_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('project_instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measured_variable', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('power_source', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('process_connection', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('cable_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plc_panel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_project_instruments_cable_id', 'project_cables', ['cable_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_project_instruments_plc_panel_id', 'project_control_panels', ['plc_panel_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('project_io_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('io_tag', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('plc_panel_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rack', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('slot', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('channel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fail_state', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('alarm_priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'NONE', name='alarmpriority', native_enum=False), nullable=True))
        batch_op.add_column(sa.Column('scada_tag', sa.String(length=60), nullable=True))
        batch_op.create_foreign_key('fk_project_io_list_plc_panel_id', 'project_control_panels', ['plc_panel_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('project_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('room', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('process_system', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('indoor_outdoor', sa.Enum('INDOOR', 'OUTDOOR', name='indooroutdoor', native_enum=False), nullable=True))

    with op.batch_alter_table('project_panel_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('component_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('part_number', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('voltage', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('power_supply_source', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('terminal_block_reference', sa.String(length=80), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('voltage_system', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('issue_stage', sa.Enum('CONCEPT', 'PRELIMINARY', 'DESIGN_30', 'DESIGN_60', 'DESIGN_90', 'IFC', 'AS_BUILT', 'OTHER', name='issuestage', native_enum=False), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('issue_stage')
        batch_op.drop_column('voltage_system')
        batch_op.drop_column('facility')

    with op.batch_alter_table('project_panel_components', schema=None) as batch_op:
        batch_op.drop_column('terminal_block_reference')
        batch_op.drop_column('power_supply_source')
        batch_op.drop_column('voltage')
        batch_op.drop_column('part_number')
        batch_op.drop_column('component_type')

    with op.batch_alter_table('project_locations', schema=None) as batch_op:
        batch_op.drop_column('indoor_outdoor')
        batch_op.drop_column('process_system')
        batch_op.drop_column('area')
        batch_op.drop_column('room')
        batch_op.drop_column('building')

    with op.batch_alter_table('project_io_list', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_io_list_plc_panel_id', type_='foreignkey')
        batch_op.drop_column('scada_tag')
        batch_op.drop_column('alarm_priority')
        batch_op.drop_column('fail_state')
        batch_op.drop_column('channel')
        batch_op.drop_column('slot')
        batch_op.drop_column('rack')
        batch_op.drop_column('plc_panel_id')
        batch_op.drop_column('io_tag')

    with op.batch_alter_table('project_instruments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_instruments_cable_id', type_='foreignkey')
        batch_op.drop_constraint('fk_project_instruments_plc_panel_id', type_='foreignkey')
        batch_op.drop_column('plc_panel_id')
        batch_op.drop_column('cable_id')
        batch_op.drop_column('process_connection')
        batch_op.drop_column('power_source')
        batch_op.drop_column('measured_variable')

    with op.batch_alter_table('project_equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_equipment_feeder_cable_id', type_='foreignkey')
        batch_op.drop_column('drawing_reference')
        batch_op.drop_column('feeder_cable_id')
        batch_op.drop_column('fla')
        batch_op.drop_column('hp_kw')
        batch_op.drop_column('phase')
        batch_op.drop_column('voltage')
        batch_op.drop_column('equipment_type')

    with op.batch_alter_table('project_control_panels', schema=None) as batch_op:
        batch_op.drop_column('ul508a_status')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('sccr')
        batch_op.drop_column('enclosure_type')
        batch_op.drop_column('voltage')
        batch_op.drop_column('panel_type')

    with op.batch_alter_table('project_cables', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_cables_route_id', type_='foreignkey')
        batch_op.drop_column('drawing_reference')
        batch_op.drop_column('route_id')

    op.drop_table('project_terminations')
    op.drop_table('project_terminal_blocks')
    op.drop_table('project_network_devices')
    op.drop_table('project_conduits')
    op.drop_table('project_cable_routes')
    op.drop_table('project_qaqc_checks')
    op.drop_table('project_feeders')
    op.drop_table('project_drawings')
    op.drop_table('project_calculations')
    # ### end Alembic commands ###
