"""initial schema

Revision ID: 3d1c278b0f52
Revises: 
Create Date: 2026-05-22 14:44:06.963414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1c278b0f52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_cables',
    sa.Column('cable_type_code', sa.String(length=60), nullable=False),
    sa.Column('conductor_material', sa.Enum('CU', 'AL', name='conductormaterial', native_enum=False), nullable=True),
    sa.Column('insulation_type', sa.String(length=40), nullable=True),
    sa.Column('voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('conductor_count', sa.Integer(), nullable=True),
    sa.Column('conductor_size', sa.String(length=40), nullable=True),
    sa.Column('ampacity', sa.Integer(), nullable=True),
    sa.Column('shielded', sa.Boolean(), nullable=False),
    sa.Column('armored', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cable_type_code')
    )
    op.create_table('catalog_manufacturers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('project_number', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('client', sa.String(length=160), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_number')
    )
    op.create_table('catalog_devices',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('device_category', sa.Enum('RELAY', 'PLC_CPU', 'HMI', 'POWER_SUPPLY', 'CIRCUIT_BREAKER', 'TERMINAL_BLOCK', 'SURGE_PROTECTOR', 'NETWORK_SWITCH', 'OTHER', name='devicecategory', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('ratings', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_equipment',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('SWITCHGEAR', 'PANELBOARD', 'MCC', 'TRANSFORMER', 'VFD', 'ATS', 'DISCONNECT', 'OTHER', name='equipmentcategory', native_enum=False), nullable=False),
    sa.Column('model_series', sa.String(length=120), nullable=False),
    sa.Column('rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('rated_current', sa.String(length=40), nullable=True),
    sa.Column('rated_kva', sa.Float(), nullable=True),
    sa.Column('sccr_rating', sa.String(length=40), nullable=True),
    sa.Column('enclosure_type', sa.String(length=40), nullable=True),
    sa.Column('poles', sa.Integer(), nullable=True),
    sa.Column('phases', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_instruments',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('instrument_type', sa.Enum('PRESSURE', 'FLOW', 'LEVEL', 'TEMPERATURE', 'ANALYTICAL', 'POSITION', 'OTHER', name='instrumenttype', native_enum=False), nullable=False),
    sa.Column('measurement_principle', sa.String(length=80), nullable=True),
    sa.Column('model_series', sa.String(length=120), nullable=False),
    sa.Column('signal_type', sa.String(length=40), nullable=True),
    sa.Column('process_connection', sa.String(length=60), nullable=True),
    sa.Column('accuracy', sa.String(length=60), nullable=True),
    sa.Column('power_requirement', sa.String(length=60), nullable=True),
    sa.Column('area_classification', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_io_modules',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('module_model', sa.String(length=120), nullable=False),
    sa.Column('io_type', sa.Enum('AI', 'AO', 'DI', 'DO', 'RTD', 'TC', 'COMM', 'OTHER', name='iotype', native_enum=False), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=True),
    sa.Column('signal_range', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_locations',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area_classification', sa.String(length=80), nullable=True),
    sa.Column('parent_location_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'location_code', name='uq_project_location_code')
    )
    op.create_table('project_control_panels',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('panel_tag', sa.String(length=60), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'panel_tag', name='uq_project_control_panel_tag')
    )
    op.create_table('project_equipment',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('catalog_equipment_id', sa.Integer(), nullable=True),
    sa.Column('equipment_tag', sa.String(length=60), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('fed_from_id', sa.Integer(), nullable=True),
    sa.Column('project_settings', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local_manufacturer', sa.String(length=120), nullable=True),
    sa.Column('local_category', sa.Enum('SWITCHGEAR', 'PANELBOARD', 'MCC', 'TRANSFORMER', 'VFD', 'ATS', 'DISCONNECT', 'OTHER', name='equipmentcategory', native_enum=False), nullable=True),
    sa.Column('local_model', sa.String(length=120), nullable=True),
    sa.Column('local_rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('local_rated_current', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('catalog_equipment_id IS NOT NULL OR local_model IS NOT NULL', name='ck_project_equipment_catalog_or_custom'),
    sa.ForeignKeyConstraint(['catalog_equipment_id'], ['catalog_equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fed_from_id'], ['project_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'equipment_tag', name='uq_project_equipment_tag')
    )
    op.create_table('project_cables',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('catalog_cable_id', sa.Integer(), nullable=True),
    sa.Column('cable_tag', sa.String(length=60), nullable=False),
    sa.Column('from_equipment_id', sa.Integer(), nullable=True),
    sa.Column('to_equipment_id', sa.Integer(), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('routing', sa.String(length=160), nullable=True),
    sa.Column('voltage_class', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local_cable_type_code', sa.String(length=60), nullable=True),
    sa.Column('local_conductor_material', sa.Enum('CU', 'AL', name='conductormaterial', native_enum=False), nullable=True),
    sa.Column('local_conductor_size', sa.String(length=40), nullable=True),
    sa.Column('local_conductor_count', sa.Integer(), nullable=True),
    sa.Column('local_insulation_type', sa.String(length=40), nullable=True),
    sa.Column('local_voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('catalog_cable_id IS NOT NULL OR local_cable_type_code IS NOT NULL', name='ck_project_cable_catalog_or_custom'),
    sa.ForeignKeyConstraint(['catalog_cable_id'], ['catalog_cables.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_equipment_id'], ['project_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_equipment_id'], ['project_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'cable_tag', name='uq_project_cable_tag')
    )
    op.create_table('project_instruments',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('catalog_instrument_id', sa.Integer(), nullable=True),
    sa.Column('instrument_tag', sa.String(length=60), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('pid_reference', sa.String(length=60), nullable=True),
    sa.Column('loop_number', sa.String(length=40), nullable=True),
    sa.Column('calibrated_range', sa.String(length=80), nullable=True),
    sa.Column('set_point', sa.String(length=80), nullable=True),
    sa.Column('associated_equipment_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local_manufacturer', sa.String(length=120), nullable=True),
    sa.Column('local_instrument_type', sa.Enum('PRESSURE', 'FLOW', 'LEVEL', 'TEMPERATURE', 'ANALYTICAL', 'POSITION', 'OTHER', name='instrumenttype', native_enum=False), nullable=True),
    sa.Column('local_model', sa.String(length=120), nullable=True),
    sa.Column('local_signal_type', sa.String(length=40), nullable=True),
    sa.Column('local_accuracy', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('catalog_instrument_id IS NOT NULL OR local_model IS NOT NULL', name='ck_project_instrument_catalog_or_custom'),
    sa.ForeignKeyConstraint(['associated_equipment_id'], ['project_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['catalog_instrument_id'], ['catalog_instruments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['project_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'instrument_tag', name='uq_project_instrument_tag')
    )
    op.create_table('project_panel_components',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('control_panel_id', sa.Integer(), nullable=False),
    sa.Column('catalog_device_id', sa.Integer(), nullable=True),
    sa.Column('component_tag', sa.String(length=60), nullable=True),
    sa.Column('mounting_reference', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local_manufacturer', sa.String(length=120), nullable=True),
    sa.Column('local_device_category', sa.Enum('RELAY', 'PLC_CPU', 'HMI', 'POWER_SUPPLY', 'CIRCUIT_BREAKER', 'TERMINAL_BLOCK', 'SURGE_PROTECTOR', 'NETWORK_SWITCH', 'OTHER', name='devicecategory', native_enum=False), nullable=True),
    sa.Column('local_model', sa.String(length=120), nullable=True),
    sa.Column('local_ratings', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('catalog_device_id IS NOT NULL OR local_model IS NOT NULL', name='ck_project_panel_component_catalog_or_custom'),
    sa.ForeignKeyConstraint(['catalog_device_id'], ['catalog_devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['control_panel_id'], ['project_control_panels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_io_list',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('catalog_io_module_id', sa.Integer(), nullable=True),
    sa.Column('project_instrument_id', sa.Integer(), nullable=True),
    sa.Column('project_panel_component_id', sa.Integer(), nullable=True),
    sa.Column('io_type', sa.Enum('AI', 'AO', 'DI', 'DO', 'RTD', 'TC', 'COMM', 'OTHER', name='iotype', native_enum=False), nullable=False),
    sa.Column('plc_address', sa.String(length=60), nullable=True),
    sa.Column('signal_range', sa.String(length=60), nullable=True),
    sa.Column('cable_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('local_io_module_model', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('catalog_io_module_id IS NOT NULL OR local_io_module_model IS NOT NULL', name='ck_project_io_catalog_or_custom'),
    sa.ForeignKeyConstraint(['cable_id'], ['project_cables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['catalog_io_module_id'], ['catalog_io_modules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_instrument_id'], ['project_instruments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_panel_component_id'], ['project_panel_components.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_panel_circuits',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('circuit_number', sa.String(length=20), nullable=False),
    sa.Column('load_description', sa.String(length=160), nullable=True),
    sa.Column('connected_load', sa.Float(), nullable=True),
    sa.Column('phases', sa.String(length=20), nullable=True),
    sa.Column('breaker_size', sa.String(length=40), nullable=True),
    sa.Column('cable_id', sa.Integer(), nullable=True),
    sa.Column('destination_equipment_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cable_id'], ['project_cables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_equipment_id'], ['project_equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['panel_id'], ['project_equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'circuit_number', name='uq_project_panel_circuit_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_panel_circuits')
    op.drop_table('project_io_list')
    op.drop_table('project_panel_components')
    op.drop_table('project_instruments')
    op.drop_table('project_cables')
    op.drop_table('project_equipment')
    op.drop_table('project_control_panels')
    op.drop_table('project_locations')
    op.drop_table('catalog_io_modules')
    op.drop_table('catalog_instruments')
    op.drop_table('catalog_equipment')
    op.drop_table('catalog_devices')
    op.drop_table('projects')
    op.drop_table('catalog_manufacturers')
    op.drop_table('catalog_cables')
    # ### end Alembic commands ###
