"""add_catalog_groups_and_extended_tables

Revision ID: af7e43fe52d7
Revises: 0db355f1563c
Create Date: 2026-05-22 22:18:55.648728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7e43fe52d7'
down_revision: Union[str, None] = '0db355f1563c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_groups',
    sa.Column('parent_group_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('group_code', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('linked_table', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_group_id'], ['catalog_groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code')
    )
    with op.batch_alter_table('catalog_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalog_groups_parent_group_id'), ['parent_group_id'], unique=False)

    op.create_table('cat_area_types',
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_area_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_area_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_cable_insulations',
    sa.Column('material', sa.String(length=60), nullable=True),
    sa.Column('voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('temperature_rating', sa.String(length=20), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_cable_insulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_cable_insulations_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_cable_trays',
    sa.Column('material', sa.String(length=40), nullable=True),
    sa.Column('width_in', sa.String(length=20), nullable=True),
    sa.Column('depth_in', sa.String(length=20), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_cable_trays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_cable_trays_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_comm_protocols',
    sa.Column('layer', sa.String(length=40), nullable=True),
    sa.Column('medium', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_comm_protocols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_comm_protocols_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_conductor_materials',
    sa.Column('resistivity', sa.String(length=60), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_conductor_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_conductor_materials_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_conduit_routing',
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_conduit_routing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_conduit_routing_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_conduit_types',
    sa.Column('material', sa.String(length=40), nullable=True),
    sa.Column('trade_size', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_conduit_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_conduit_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_document_types',
    sa.Column('discipline', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_document_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_drawing_types',
    sa.Column('discipline', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_drawing_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_drawing_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_enclosures',
    sa.Column('standard', sa.String(length=40), nullable=True),
    sa.Column('ip_rating', sa.String(length=20), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_enclosures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_enclosures_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_environmental_ratings',
    sa.Column('standard', sa.String(length=40), nullable=True),
    sa.Column('ip_equivalent', sa.String(length=20), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_environmental_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_environmental_ratings_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_equipment_types',
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_equipment_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_equipment_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_grounding_types',
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_grounding_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_grounding_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_hazardous_areas',
    sa.Column('classification_standard', sa.String(length=40), nullable=True),
    sa.Column('class_division', sa.String(length=40), nullable=True),
    sa.Column('group', sa.String(length=20), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_hazardous_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_hazardous_areas_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_installation_methods',
    sa.Column('nec_article', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_installation_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_installation_methods_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_measurement_types',
    sa.Column('unit_of_measure', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_measurement_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_measurement_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_mounting_details',
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_mounting_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_mounting_details_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_mounting_types',
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_mounting_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_mounting_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_phase_wire_configs',
    sa.Column('phase_count', sa.Integer(), nullable=True),
    sa.Column('wire_count', sa.Integer(), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_phase_wire_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_phase_wire_configs_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_power_systems',
    sa.Column('nominal_voltage', sa.String(length=40), nullable=True),
    sa.Column('frequency_hz', sa.Float(), nullable=True),
    sa.Column('phases', sa.Integer(), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_power_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_power_systems_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_process_connections',
    sa.Column('connection_size', sa.String(length=40), nullable=True),
    sa.Column('connection_standard', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_process_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_process_connections_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_revision_statuses',
    sa.Column('is_issued', sa.Boolean(), nullable=False),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_revision_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_revision_statuses_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_room_types',
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_room_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_room_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_signal_types',
    sa.Column('signal_range', sa.String(length=60), nullable=True),
    sa.Column('protocol', sa.String(length=60), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_signal_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_signal_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_submittal_statuses',
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_submittal_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_submittal_statuses_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_termination_types',
    sa.Column('compatible_wire_range', sa.String(length=60), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_termination_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_termination_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_voltage_classes',
    sa.Column('voltage_value', sa.String(length=40), nullable=True),
    sa.Column('voltage_range', sa.String(length=80), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_voltage_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_voltage_classes_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_wire_types',
    sa.Column('voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('temperature_rating', sa.String(length=20), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_wire_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_wire_types_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('project_pipeline_progress',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.String(length=60), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'step_id', name='uq_pipeline_progress_step')
    )
    op.create_table('cat_ats',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('rated_current', sa.String(length=40), nullable=True),
    sa.Column('poles', sa.Integer(), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_ats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_ats_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_breakers',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('frame_rating', sa.String(length=40), nullable=True),
    sa.Column('trip_rating', sa.String(length=40), nullable=True),
    sa.Column('interrupt_rating', sa.String(length=40), nullable=True),
    sa.Column('poles', sa.Integer(), nullable=True),
    sa.Column('voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_breakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_breakers_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_disconnect_switches',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('amp_rating', sa.String(length=40), nullable=True),
    sa.Column('voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('fusible', sa.Boolean(), nullable=False),
    sa.Column('poles', sa.Integer(), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_disconnect_switches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_disconnect_switches_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_equipment_models',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('equipment_type_id', sa.Integer(), nullable=True),
    sa.Column('rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('rated_current', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['cat_equipment_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_equipment_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_equipment_models_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_fuses',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('amp_rating', sa.String(length=40), nullable=True),
    sa.Column('voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('class_type', sa.String(length=20), nullable=True),
    sa.Column('interrupt_rating', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_fuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_fuses_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_generators',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('rated_kw', sa.Float(), nullable=True),
    sa.Column('rated_kva', sa.Float(), nullable=True),
    sa.Column('rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('fuel_type', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_generators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_generators_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_instrument_models',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('instrument_type', sa.String(length=60), nullable=True),
    sa.Column('signal_type', sa.String(length=40), nullable=True),
    sa.Column('accuracy', sa.String(length=60), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_instrument_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_instrument_models_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_mccs',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('bus_rating', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_mccs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_mccs_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_network_devices',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=60), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_network_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_network_devices_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_overloads',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('amp_range', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_overloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_overloads_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_panelboards',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('rated_current', sa.String(length=40), nullable=True),
    sa.Column('poles', sa.Integer(), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_panelboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_panelboards_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_plc_io',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('io_type', sa.String(length=20), nullable=True),
    sa.Column('point_count', sa.Integer(), nullable=True),
    sa.Column('signal_range', sa.String(length=60), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_plc_io', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_plc_io_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_plcs',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('processor_model', sa.String(length=120), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('communication_ports', sa.String(length=120), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_plcs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_plcs_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_relays',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('relay_type', sa.String(length=60), nullable=True),
    sa.Column('coil_voltage', sa.String(length=40), nullable=True),
    sa.Column('contact_config', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_relays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_relays_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_scada',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('platform_type', sa.String(length=60), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_scada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_scada_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_soft_starters',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('hp_rating', sa.String(length=40), nullable=True),
    sa.Column('amp_rating', sa.String(length=40), nullable=True),
    sa.Column('voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_soft_starters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_soft_starters_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_switchboards',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('rated_current', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_switchboards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_switchboards_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_switchgear',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('rated_voltage', sa.String(length=40), nullable=True),
    sa.Column('rated_current', sa.String(length=40), nullable=True),
    sa.Column('sccr_rating', sa.String(length=40), nullable=True),
    sa.Column('phases', sa.Integer(), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_switchgear', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_switchgear_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_transformers',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('kva_rating', sa.Float(), nullable=True),
    sa.Column('primary_voltage', sa.String(length=40), nullable=True),
    sa.Column('secondary_voltage', sa.String(length=40), nullable=True),
    sa.Column('winding_config', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_transformers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_transformers_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_ups',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('rated_kva', sa.Float(), nullable=True),
    sa.Column('battery_runtime_min', sa.Integer(), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_ups_catalog_group_id'), ['catalog_group_id'], unique=False)

    op.create_table('cat_vfds',
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('hp_rating', sa.String(length=40), nullable=True),
    sa.Column('amp_rating', sa.String(length=40), nullable=True),
    sa.Column('voltage_rating', sa.String(length=40), nullable=True),
    sa.Column('catalog_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_group_id'], ['catalog_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['catalog_manufacturers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_vfds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cat_vfds_catalog_group_id'), ['catalog_group_id'], unique=False)

    # erd_relationships and erd_node_positions are lazily created by the ERD
    # router at runtime; they are not part of the managed schema.
    with op.batch_alter_table('catalog_cables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_catalog_cables_catalog_group_id'), ['catalog_group_id'], unique=False)
        batch_op.create_foreign_key('fk_catalog_cables_group', 'catalog_groups', ['catalog_group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('catalog_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_catalog_devices_catalog_group_id'), ['catalog_group_id'], unique=False)
        batch_op.create_foreign_key('fk_catalog_devices_group', 'catalog_groups', ['catalog_group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('catalog_equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_catalog_equipment_catalog_group_id'), ['catalog_group_id'], unique=False)
        batch_op.create_foreign_key('fk_catalog_equipment_group', 'catalog_groups', ['catalog_group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('catalog_instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_catalog_instruments_catalog_group_id'), ['catalog_group_id'], unique=False)
        batch_op.create_foreign_key('fk_catalog_instruments_group', 'catalog_groups', ['catalog_group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('catalog_io_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_catalog_io_modules_catalog_group_id'), ['catalog_group_id'], unique=False)
        batch_op.create_foreign_key('fk_catalog_io_modules_group', 'catalog_groups', ['catalog_group_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('catalog_manufacturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_group_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_catalog_manufacturers_catalog_group_id'), ['catalog_group_id'], unique=False)
        batch_op.create_foreign_key('fk_catalog_manufacturers_group', 'catalog_groups', ['catalog_group_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalog_manufacturers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catalog_manufacturers_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_catalog_manufacturers_catalog_group_id'))
        batch_op.drop_column('catalog_group_id')

    with op.batch_alter_table('catalog_io_modules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catalog_io_modules_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_catalog_io_modules_catalog_group_id'))
        batch_op.drop_column('catalog_group_id')

    with op.batch_alter_table('catalog_instruments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catalog_instruments_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_catalog_instruments_catalog_group_id'))
        batch_op.drop_column('catalog_group_id')

    with op.batch_alter_table('catalog_equipment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catalog_equipment_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_catalog_equipment_catalog_group_id'))
        batch_op.drop_column('catalog_group_id')

    with op.batch_alter_table('catalog_devices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catalog_devices_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_catalog_devices_catalog_group_id'))
        batch_op.drop_column('catalog_group_id')

    with op.batch_alter_table('catalog_cables', schema=None) as batch_op:
        batch_op.drop_constraint('fk_catalog_cables_group', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_catalog_cables_catalog_group_id'))
        batch_op.drop_column('catalog_group_id')

    op.create_table('erd_node_positions',
    sa.Column('table_name', sa.TEXT(), nullable=True),
    sa.Column('x', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('y', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('collapsed', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_table('erd_relationships',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('parent_table', sa.TEXT(), nullable=False),
    sa.Column('child_table', sa.TEXT(), nullable=False),
    sa.Column('foreign_key', sa.TEXT(), nullable=True),
    sa.Column('rel_type', sa.TEXT(), server_default=sa.text("'ONE_TO_MANY'"), nullable=False),
    sa.Column('cascade_update', sa.TEXT(), server_default=sa.text("'NO ACTION'"), nullable=False),
    sa.Column('cascade_delete', sa.TEXT(), server_default=sa.text("'NO ACTION'"), nullable=False),
    sa.Column('label', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cat_vfds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_vfds_catalog_group_id'))

    op.drop_table('cat_vfds')
    with op.batch_alter_table('cat_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_ups_catalog_group_id'))

    op.drop_table('cat_ups')
    with op.batch_alter_table('cat_transformers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_transformers_catalog_group_id'))

    op.drop_table('cat_transformers')
    with op.batch_alter_table('cat_switchgear', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_switchgear_catalog_group_id'))

    op.drop_table('cat_switchgear')
    with op.batch_alter_table('cat_switchboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_switchboards_catalog_group_id'))

    op.drop_table('cat_switchboards')
    with op.batch_alter_table('cat_soft_starters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_soft_starters_catalog_group_id'))

    op.drop_table('cat_soft_starters')
    with op.batch_alter_table('cat_scada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_scada_catalog_group_id'))

    op.drop_table('cat_scada')
    with op.batch_alter_table('cat_relays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_relays_catalog_group_id'))

    op.drop_table('cat_relays')
    with op.batch_alter_table('cat_plcs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_plcs_catalog_group_id'))

    op.drop_table('cat_plcs')
    with op.batch_alter_table('cat_plc_io', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_plc_io_catalog_group_id'))

    op.drop_table('cat_plc_io')
    with op.batch_alter_table('cat_panelboards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_panelboards_catalog_group_id'))

    op.drop_table('cat_panelboards')
    with op.batch_alter_table('cat_overloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_overloads_catalog_group_id'))

    op.drop_table('cat_overloads')
    with op.batch_alter_table('cat_network_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_network_devices_catalog_group_id'))

    op.drop_table('cat_network_devices')
    with op.batch_alter_table('cat_mccs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_mccs_catalog_group_id'))

    op.drop_table('cat_mccs')
    with op.batch_alter_table('cat_instrument_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_instrument_models_catalog_group_id'))

    op.drop_table('cat_instrument_models')
    with op.batch_alter_table('cat_generators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_generators_catalog_group_id'))

    op.drop_table('cat_generators')
    with op.batch_alter_table('cat_fuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_fuses_catalog_group_id'))

    op.drop_table('cat_fuses')
    with op.batch_alter_table('cat_equipment_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_equipment_models_catalog_group_id'))

    op.drop_table('cat_equipment_models')
    with op.batch_alter_table('cat_disconnect_switches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_disconnect_switches_catalog_group_id'))

    op.drop_table('cat_disconnect_switches')
    with op.batch_alter_table('cat_breakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_breakers_catalog_group_id'))

    op.drop_table('cat_breakers')
    with op.batch_alter_table('cat_ats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_ats_catalog_group_id'))

    op.drop_table('cat_ats')
    op.drop_table('project_pipeline_progress')
    with op.batch_alter_table('cat_wire_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_wire_types_catalog_group_id'))

    op.drop_table('cat_wire_types')
    with op.batch_alter_table('cat_voltage_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_voltage_classes_catalog_group_id'))

    op.drop_table('cat_voltage_classes')
    with op.batch_alter_table('cat_termination_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_termination_types_catalog_group_id'))

    op.drop_table('cat_termination_types')
    with op.batch_alter_table('cat_submittal_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_submittal_statuses_catalog_group_id'))

    op.drop_table('cat_submittal_statuses')
    with op.batch_alter_table('cat_signal_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_signal_types_catalog_group_id'))

    op.drop_table('cat_signal_types')
    with op.batch_alter_table('cat_room_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_room_types_catalog_group_id'))

    op.drop_table('cat_room_types')
    with op.batch_alter_table('cat_revision_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_revision_statuses_catalog_group_id'))

    op.drop_table('cat_revision_statuses')
    with op.batch_alter_table('cat_process_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_process_connections_catalog_group_id'))

    op.drop_table('cat_process_connections')
    with op.batch_alter_table('cat_power_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_power_systems_catalog_group_id'))

    op.drop_table('cat_power_systems')
    with op.batch_alter_table('cat_phase_wire_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_phase_wire_configs_catalog_group_id'))

    op.drop_table('cat_phase_wire_configs')
    with op.batch_alter_table('cat_mounting_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_mounting_types_catalog_group_id'))

    op.drop_table('cat_mounting_types')
    with op.batch_alter_table('cat_mounting_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_mounting_details_catalog_group_id'))

    op.drop_table('cat_mounting_details')
    with op.batch_alter_table('cat_measurement_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_measurement_types_catalog_group_id'))

    op.drop_table('cat_measurement_types')
    with op.batch_alter_table('cat_installation_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_installation_methods_catalog_group_id'))

    op.drop_table('cat_installation_methods')
    with op.batch_alter_table('cat_hazardous_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_hazardous_areas_catalog_group_id'))

    op.drop_table('cat_hazardous_areas')
    with op.batch_alter_table('cat_grounding_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_grounding_types_catalog_group_id'))

    op.drop_table('cat_grounding_types')
    with op.batch_alter_table('cat_equipment_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_equipment_types_catalog_group_id'))

    op.drop_table('cat_equipment_types')
    with op.batch_alter_table('cat_environmental_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_environmental_ratings_catalog_group_id'))

    op.drop_table('cat_environmental_ratings')
    with op.batch_alter_table('cat_enclosures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_enclosures_catalog_group_id'))

    op.drop_table('cat_enclosures')
    with op.batch_alter_table('cat_drawing_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_drawing_types_catalog_group_id'))

    op.drop_table('cat_drawing_types')
    with op.batch_alter_table('cat_document_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_document_types_catalog_group_id'))

    op.drop_table('cat_document_types')
    with op.batch_alter_table('cat_conduit_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_conduit_types_catalog_group_id'))

    op.drop_table('cat_conduit_types')
    with op.batch_alter_table('cat_conduit_routing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_conduit_routing_catalog_group_id'))

    op.drop_table('cat_conduit_routing')
    with op.batch_alter_table('cat_conductor_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_conductor_materials_catalog_group_id'))

    op.drop_table('cat_conductor_materials')
    with op.batch_alter_table('cat_comm_protocols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_comm_protocols_catalog_group_id'))

    op.drop_table('cat_comm_protocols')
    with op.batch_alter_table('cat_cable_trays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_cable_trays_catalog_group_id'))

    op.drop_table('cat_cable_trays')
    with op.batch_alter_table('cat_cable_insulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_cable_insulations_catalog_group_id'))

    op.drop_table('cat_cable_insulations')
    with op.batch_alter_table('cat_area_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cat_area_types_catalog_group_id'))

    op.drop_table('cat_area_types')
    with op.batch_alter_table('catalog_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalog_groups_parent_group_id'))

    op.drop_table('catalog_groups')
    # ### end Alembic commands ###
