// Chapter metadata -- the single source of truth for the UI.
//
// Every table ("chapter") is described here: its fields, which are foreign
// keys, which are enums, and -- for the five catalog-linked Class B tables --
// how it merges with its Class A catalog.  The generic grid and form
// components render any chapter purely from this metadata, so adding a column
// is a one-line change here, not a new component.

import type { ChapterDef } from "./types";

// Enum value lists.  These mirror app/models/enums.py on the backend.
export const ENUMS = {
  EquipmentCategory: [
    "SWITCHGEAR",
    "PANELBOARD",
    "MCC",
    "TRANSFORMER",
    "VFD",
    "ATS",
    "DISCONNECT",
    "OTHER",
  ],
  ConductorMaterial: ["CU", "AL"],
  InstrumentType: [
    "PRESSURE",
    "FLOW",
    "LEVEL",
    "TEMPERATURE",
    "ANALYTICAL",
    "POSITION",
    "OTHER",
  ],
  IOType: ["AI", "AO", "DI", "DO", "RTD", "TC", "COMM", "OTHER"],
  DeviceCategory: [
    "RELAY",
    "PLC_CPU",
    "HMI",
    "POWER_SUPPLY",
    "CIRCUIT_BREAKER",
    "TERMINAL_BLOCK",
    "SURGE_PROTECTOR",
    "NETWORK_SWITCH",
    "OTHER",
  ],
  ProjectStatus: ["PLANNING", "ACTIVE", "ON_HOLD", "COMPLETED", "ARCHIVED"],
  IssueStage: [
    "CONCEPT",
    "PRELIMINARY",
    "DESIGN_30",
    "DESIGN_60",
    "DESIGN_90",
    "IFC",
    "AS_BUILT",
    "OTHER",
  ],
  IndoorOutdoor: ["INDOOR", "OUTDOOR"],
  UL508AStatus: ["LISTED", "NOT_LISTED", "PENDING", "NOT_APPLICABLE"],
  RouteType: ["TRAY", "CONDUIT", "DUCTBANK", "DIRECT_BURIED", "FREE_AIR", "OTHER"],
  ConduitType: ["CONDUIT", "CABLE_TRAY", "DUCTBANK", "WIREWAY"],
  ConduitMaterial: [
    "PVC",
    "RMC",
    "EMT",
    "IMC",
    "ALUMINUM",
    "GALV_STEEL",
    "FIBERGLASS",
    "OTHER",
  ],
  CableEnd: ["FROM", "TO"],
  TerminationType: [
    "LUG",
    "RING",
    "FERRULE",
    "TERMINAL_BLOCK",
    "SPLICE",
    "DIRECT",
    "OTHER",
  ],
  NetworkDeviceType: [
    "SWITCH",
    "ROUTER",
    "GATEWAY",
    "FIREWALL",
    "ACCESS_POINT",
    "MEDIA_CONVERTER",
    "OTHER",
  ],
  NetworkProtocol: [
    "ETHERNET_IP",
    "MODBUS_TCP",
    "PROFINET",
    "OPC_UA",
    "DNP3",
    "BACNET",
    "OTHER",
  ],
  DrawingType: [
    "ONE_LINE",
    "SCHEMATIC",
    "PANEL_LAYOUT",
    "LOOP_DIAGRAM",
    "PID",
    "LOCATION_PLAN",
    "CABLE_ROUTING",
    "DETAIL",
    "OTHER",
  ],
  DrawingStatus: ["PRELIMINARY", "IFR", "IFA", "IFB", "IFC", "AS_BUILT", "OTHER"],
  CalcType: [
    "LOAD",
    "VOLTAGE_DROP",
    "SHORT_CIRCUIT",
    "CONDUIT_FILL",
    "GROUNDING",
    "LIGHTING",
    "CABLE_AMPACITY",
    "ARC_FLASH",
    "OTHER",
  ],
  CalcStatus: [
    "PRELIMINARY",
    "IN_PROGRESS",
    "COMPLETE",
    "CHECKED",
    "APPROVED",
    "OTHER",
  ],
  QAQCCategory: [
    "TAGGING",
    "POWER",
    "CABLES",
    "INSTRUMENTS",
    "IO",
    "TERMINATIONS",
    "DRAWINGS",
    "GENERAL",
    "OTHER",
  ],
  QAQCStatus: ["OPEN", "PASS", "FAIL", "NOT_APPLICABLE", "RESOLVED"],
  QAQCSeverity: ["CRITICAL", "MAJOR", "MINOR"],
  AlarmPriority: ["CRITICAL", "HIGH", "MEDIUM", "LOW", "NONE"],
};

export const CHAPTERS: ChapterDef[] = [
  // =======================================================================
  // CLASS A -- GENERAL CATALOGS
  // =======================================================================
  {
    key: "catalog-manufacturers",
    title: "Manufacturers",
    group: "catalog",
    projectScoped: false,
    fkLabelField: "name",
    gridFields: ["name", "abbreviation", "country"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "abbreviation", label: "Abbreviation", type: "text" },
      { name: "country", label: "Country", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "catalog-equipment",
    title: "Equipment",
    group: "catalog",
    projectScoped: false,
    fkLabelField: "model_series",
    gridFields: [
      "model_series",
      "category",
      "manufacturer_id",
      "rated_voltage",
      "rated_current",
    ],
    fields: [
      {
        name: "manufacturer_id",
        label: "Manufacturer",
        type: "fk",
        fkChapter: "catalog-manufacturers",
      },
      {
        name: "category",
        label: "Category",
        type: "enum",
        required: true,
        options: ENUMS.EquipmentCategory,
      },
      { name: "model_series", label: "Model / Series", type: "text", required: true },
      { name: "rated_voltage", label: "Rated Voltage", type: "text" },
      { name: "rated_current", label: "Rated Current", type: "text" },
      { name: "rated_kva", label: "Rated kVA", type: "number" },
      { name: "sccr_rating", label: "SCCR / AIC", type: "text" },
      { name: "enclosure_type", label: "Enclosure (NEMA)", type: "text" },
      { name: "poles", label: "Poles", type: "number" },
      { name: "phases", label: "Phases", type: "number" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "catalog-cables",
    title: "Cables",
    group: "catalog",
    projectScoped: false,
    fkLabelField: "cable_type_code",
    gridFields: [
      "cable_type_code",
      "conductor_material",
      "conductor_size",
      "conductor_count",
      "voltage_rating",
      "ampacity",
    ],
    fields: [
      { name: "cable_type_code", label: "Cable Type Code", type: "text", required: true },
      {
        name: "conductor_material",
        label: "Conductor Material",
        type: "enum",
        options: ENUMS.ConductorMaterial,
      },
      { name: "insulation_type", label: "Insulation Type", type: "text" },
      { name: "voltage_rating", label: "Voltage Rating", type: "text" },
      { name: "conductor_count", label: "Conductor Count", type: "number" },
      { name: "conductor_size", label: "Conductor Size (AWG/kcmil)", type: "text" },
      { name: "ampacity", label: "Ampacity (A)", type: "number" },
      { name: "shielded", label: "Shielded", type: "bool" },
      { name: "armored", label: "Armored", type: "bool" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "catalog-instruments",
    title: "Instruments",
    group: "catalog",
    projectScoped: false,
    fkLabelField: "model_series",
    gridFields: [
      "model_series",
      "instrument_type",
      "manufacturer_id",
      "signal_type",
      "accuracy",
    ],
    fields: [
      {
        name: "manufacturer_id",
        label: "Manufacturer",
        type: "fk",
        fkChapter: "catalog-manufacturers",
      },
      {
        name: "instrument_type",
        label: "Instrument Type",
        type: "enum",
        required: true,
        options: ENUMS.InstrumentType,
      },
      { name: "measurement_principle", label: "Measurement Principle", type: "text" },
      { name: "model_series", label: "Model / Series", type: "text", required: true },
      { name: "signal_type", label: "Signal Type", type: "text" },
      { name: "process_connection", label: "Process Connection", type: "text" },
      { name: "accuracy", label: "Accuracy", type: "text" },
      { name: "power_requirement", label: "Power Requirement", type: "text" },
      { name: "area_classification", label: "Area Classification", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "catalog-io-modules",
    title: "I/O Modules",
    group: "catalog",
    projectScoped: false,
    fkLabelField: "module_model",
    gridFields: [
      "module_model",
      "io_type",
      "manufacturer_id",
      "point_count",
      "signal_range",
    ],
    fields: [
      {
        name: "manufacturer_id",
        label: "Manufacturer",
        type: "fk",
        fkChapter: "catalog-manufacturers",
      },
      { name: "module_model", label: "Module Model", type: "text", required: true },
      {
        name: "io_type",
        label: "I/O Type",
        type: "enum",
        required: true,
        options: ENUMS.IOType,
      },
      { name: "point_count", label: "Point Count", type: "number" },
      { name: "signal_range", label: "Signal Range", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "catalog-devices",
    title: "Devices",
    group: "catalog",
    projectScoped: false,
    fkLabelField: "model",
    gridFields: ["model", "device_category", "manufacturer_id", "ratings"],
    fields: [
      {
        name: "manufacturer_id",
        label: "Manufacturer",
        type: "fk",
        fkChapter: "catalog-manufacturers",
      },
      {
        name: "device_category",
        label: "Device Category",
        type: "enum",
        required: true,
        options: ENUMS.DeviceCategory,
      },
      { name: "model", label: "Model", type: "text", required: true },
      { name: "ratings", label: "Ratings", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },

  // =======================================================================
  // CLASS B -- PROJECT TABLES
  // =======================================================================
  {
    key: "projects",
    title: "Projects",
    group: "project",
    projectScoped: false, // the registry itself is not filtered by a project
    fkLabelField: "name",
    gridFields: ["project_number", "name", "client", "facility", "status"],
    fields: [
      { name: "project_number", label: "Project Number", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "client", label: "Client", type: "text" },
      { name: "facility", label: "Facility", type: "text" },
      { name: "location", label: "Location", type: "text" },
      { name: "voltage_system", label: "Voltage System", type: "text" },
      {
        name: "issue_stage",
        label: "Issue Stage",
        type: "enum",
        options: ENUMS.IssueStage,
      },
      {
        name: "status",
        label: "Status",
        type: "enum",
        required: true,
        options: ENUMS.ProjectStatus,
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-locations",
    title: "Locations / Areas",
    group: "project",
    projectScoped: true,
    fkLabelField: "location_code",
    gridFields: ["location_code", "typical_facility", "building", "area", "indoor_outdoor"],
    fields: [
      { name: "location_code", label: "Location Code", type: "text", required: true },
      { name: "typical_facility", label: "Typical Facility", type: "enum", options: ["Water Treatment Plant", "Cement Plant", "Manufacturing / Industrial", "Substation", "Oil & Gas", "Data Center", "General"] },
      { name: "building", label: "Building", type: "text" },
      { name: "room", label: "Room", type: "text" },
      { name: "area", label: "Area", type: "text" },
      { name: "process_system", label: "Process System", type: "text" },
      {
        name: "indoor_outdoor",
        label: "Indoor / Outdoor",
        type: "enum",
        options: ENUMS.IndoorOutdoor,
      },
      { name: "area_classification", label: "Hazardous Classification", type: "text" },
      {
        name: "parent_location_id",
        label: "Parent Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-feeders",
    title: "Power Distribution",
    group: "project",
    projectScoped: true,
    fkLabelField: "feeder_tag",
    gridFields: [
      "feeder_tag",
      "source_equipment_id",
      "load_equipment_id",
      "voltage",
      "ocpd_rating",
    ],
    fields: [
      { name: "feeder_tag", label: "Feeder Tag", type: "text", required: true },
      {
        name: "source_equipment_id",
        label: "Source Equipment",
        type: "fk",
        fkChapter: "project-equipment",
      },
      {
        name: "load_equipment_id",
        label: "Load Equipment",
        type: "fk",
        fkChapter: "project-equipment",
      },
      { name: "voltage", label: "Voltage", type: "text" },
      { name: "phases", label: "Phases", type: "text" },
      { name: "ampacity", label: "Ampacity", type: "text" },
      { name: "ocpd_type", label: "OCPD Type", type: "text" },
      { name: "ocpd_rating", label: "OCPD Rating", type: "text" },
      {
        name: "feeder_cable_id",
        label: "Feeder Cable",
        type: "fk",
        fkChapter: "project-cables",
      },
      { name: "drawing_reference", label: "Drawing Reference", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-equipment",
    title: "Equipment",
    group: "project",
    projectScoped: true,
    fkLabelField: "equipment_tag",
    merge: {
      catalogChapter: "catalog-equipment",
      catalogFkField: "catalog_equipment_id",
      catalogLabelFields: ["model_series", "category"],
      primaryLocalField: "local_model",
    },
    gridFields: ["equipment_tag", "equipment_type", "__source__", "voltage", "location_id"],
    fields: [
      { name: "equipment_tag", label: "Equipment Tag", type: "text", required: true },
      { name: "equipment_type", label: "Equipment Type", type: "text" },
      {
        name: "location_id",
        label: "Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      { name: "voltage", label: "Voltage", type: "text" },
      { name: "phase", label: "Phase", type: "text" },
      { name: "hp_kw", label: "HP / kW", type: "text" },
      { name: "fla", label: "FLA (A)", type: "number" },
      {
        name: "fed_from_id",
        label: "Source Panel (Fed From)",
        type: "fk",
        fkChapter: "project-equipment",
      },
      {
        name: "feeder_cable_id",
        label: "Feeder Cable",
        type: "fk",
        fkChapter: "project-cables",
      },
      { name: "drawing_reference", label: "Drawing Reference", type: "text" },
      { name: "project_settings", label: "Settings / Overrides", type: "textarea" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
      // local permanent attributes (custom / one-off path)
      { name: "local_manufacturer", label: "Manufacturer", type: "text", local: true },
      {
        name: "local_category",
        label: "Category",
        type: "enum",
        options: ENUMS.EquipmentCategory,
        local: true,
      },
      { name: "local_model", label: "Model", type: "text", local: true },
      { name: "local_rated_voltage", label: "Rated Voltage", type: "text", local: true },
      { name: "local_rated_current", label: "Rated Current", type: "text", local: true },
    ],
  },
  {
    key: "project-control-panels",
    title: "Control Panels",
    group: "project",
    projectScoped: true,
    fkLabelField: "panel_tag",
    gridFields: ["panel_tag", "panel_type", "voltage", "enclosure_type", "ul508a_status"],
    fields: [
      { name: "panel_tag", label: "Panel Tag", type: "text", required: true },
      { name: "panel_type", label: "Panel Type", type: "text" },
      { name: "voltage", label: "Voltage", type: "text" },
      { name: "enclosure_type", label: "Enclosure Type", type: "text" },
      { name: "sccr", label: "SCCR", type: "text" },
      { name: "manufacturer", label: "Manufacturer", type: "text" },
      {
        name: "ul508a_status",
        label: "UL 508A Status",
        type: "enum",
        options: ENUMS.UL508AStatus,
      },
      {
        name: "location_id",
        label: "Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-panel-components",
    title: "Panel Components",
    group: "project",
    projectScoped: true,
    fkLabelField: "component_tag",
    merge: {
      catalogChapter: "catalog-devices",
      catalogFkField: "catalog_device_id",
      catalogLabelFields: ["model", "device_category"],
      primaryLocalField: "local_model",
    },
    gridFields: ["component_tag", "component_type", "__source__", "control_panel_id", "quantity"],
    fields: [
      {
        name: "control_panel_id",
        label: "Control Panel",
        type: "fk",
        fkChapter: "project-control-panels",
        required: true,
      },
      { name: "component_tag", label: "Component Tag", type: "text" },
      { name: "component_type", label: "Component Type", type: "text" },
      { name: "part_number", label: "Part Number", type: "text" },
      { name: "voltage", label: "Voltage", type: "text" },
      { name: "power_supply_source", label: "Power Supply Source", type: "text" },
      { name: "terminal_block_reference", label: "Terminal Block Reference", type: "text" },
      { name: "mounting_reference", label: "Mounting Reference", type: "text" },
      { name: "quantity", label: "Quantity", type: "number" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
      // local permanent attributes (custom / one-off path)
      { name: "local_manufacturer", label: "Manufacturer", type: "text", local: true },
      {
        name: "local_device_category",
        label: "Device Category",
        type: "enum",
        options: ENUMS.DeviceCategory,
        local: true,
      },
      { name: "local_model", label: "Model", type: "text", local: true },
      { name: "local_ratings", label: "Ratings", type: "text", local: true },
    ],
  },
  {
    key: "project-panel-circuits",
    title: "Panel Circuits",
    group: "project",
    projectScoped: true,
    fkLabelField: "circuit_number",
    gridFields: [
      "circuit_number",
      "panel_id",
      "load_description",
      "connected_load",
      "breaker_size",
    ],
    fields: [
      {
        name: "panel_id",
        label: "Panel / MCC",
        type: "fk",
        fkChapter: "project-equipment",
        required: true,
      },
      { name: "circuit_number", label: "Circuit Number", type: "text", required: true },
      { name: "load_description", label: "Load Description", type: "text" },
      { name: "connected_load", label: "Connected Load (VA/kW)", type: "number" },
      { name: "phases", label: "Phase(s)", type: "text" },
      { name: "breaker_size", label: "Breaker / Starter Size", type: "text" },
      {
        name: "cable_id",
        label: "Cable",
        type: "fk",
        fkChapter: "project-cables",
      },
      {
        name: "destination_equipment_id",
        label: "Destination Equipment",
        type: "fk",
        fkChapter: "project-equipment",
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-cables",
    title: "Cables",
    group: "project",
    projectScoped: true,
    fkLabelField: "cable_tag",
    merge: {
      catalogChapter: "catalog-cables",
      catalogFkField: "catalog_cable_id",
      catalogLabelFields: ["cable_type_code"],
      primaryLocalField: "local_cable_type_code",
    },
    gridFields: ["cable_tag", "__source__", "from_equipment_id", "to_equipment_id", "length"],
    fields: [
      { name: "cable_tag", label: "Cable Tag", type: "text", required: true },
      {
        name: "from_equipment_id",
        label: "From Equipment",
        type: "fk",
        fkChapter: "project-equipment",
      },
      {
        name: "to_equipment_id",
        label: "To Equipment",
        type: "fk",
        fkChapter: "project-equipment",
      },
      {
        name: "from_location_id",
        label: "From Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      {
        name: "to_location_id",
        label: "To Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      { name: "length", label: "Estimated Length", type: "number" },
      { name: "routing", label: "Routing (free text)", type: "text" },
      {
        name: "route_id",
        label: "Cable Route",
        type: "fk",
        fkChapter: "project-cable-routes",
      },
      { name: "voltage_class", label: "Voltage Class", type: "text" },
      { name: "drawing_reference", label: "Drawing Reference", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
      // local permanent attributes (custom / one-off path)
      {
        name: "local_cable_type_code",
        label: "Cable Type Code",
        type: "text",
        local: true,
      },
      {
        name: "local_conductor_material",
        label: "Conductor Material",
        type: "enum",
        options: ENUMS.ConductorMaterial,
        local: true,
      },
      { name: "local_conductor_size", label: "Conductor Size", type: "text", local: true },
      {
        name: "local_conductor_count",
        label: "Conductor Count",
        type: "number",
        local: true,
      },
      {
        name: "local_insulation_type",
        label: "Insulation Type",
        type: "text",
        local: true,
      },
      {
        name: "local_voltage_rating",
        label: "Voltage Rating",
        type: "text",
        local: true,
      },
    ],
  },
  {
    key: "project-cable-routes",
    title: "Cable Routes",
    group: "project",
    projectScoped: true,
    fkLabelField: "route_tag",
    gridFields: ["route_tag", "route_type", "from_location_id", "to_location_id", "total_length"],
    fields: [
      { name: "route_tag", label: "Route Tag", type: "text", required: true },
      {
        name: "route_type",
        label: "Route Type",
        type: "enum",
        options: ENUMS.RouteType,
      },
      {
        name: "from_location_id",
        label: "From Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      {
        name: "to_location_id",
        label: "To Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      { name: "total_length", label: "Total Length", type: "number" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-conduits",
    title: "Conduits / Trays",
    group: "project",
    projectScoped: true,
    fkLabelField: "conduit_tag",
    gridFields: ["conduit_tag", "conduit_type", "trade_size", "material", "route_id"],
    fields: [
      { name: "conduit_tag", label: "Conduit / Tray Tag", type: "text", required: true },
      {
        name: "conduit_type",
        label: "Type",
        type: "enum",
        options: ENUMS.ConduitType,
      },
      { name: "trade_size", label: "Trade Size", type: "text" },
      {
        name: "material",
        label: "Material",
        type: "enum",
        options: ENUMS.ConduitMaterial,
      },
      {
        name: "route_id",
        label: "Cable Route",
        type: "fk",
        fkChapter: "project-cable-routes",
      },
      {
        name: "from_location_id",
        label: "From Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      {
        name: "to_location_id",
        label: "To Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      { name: "length", label: "Length", type: "number" },
      { name: "fill_percent", label: "Fill %", type: "number" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-instruments",
    title: "Instruments",
    group: "project",
    projectScoped: true,
    fkLabelField: "instrument_tag",
    merge: {
      catalogChapter: "catalog-instruments",
      catalogFkField: "catalog_instrument_id",
      catalogLabelFields: ["model_series", "instrument_type"],
      primaryLocalField: "local_model",
    },
    gridFields: ["instrument_tag", "__source__", "measured_variable", "location_id", "loop_number"],
    fields: [
      { name: "instrument_tag", label: "Instrument Tag (ISA)", type: "text", required: true },
      { name: "measured_variable", label: "Measured Variable", type: "text" },
      {
        name: "location_id",
        label: "Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      { name: "pid_reference", label: "P&ID Reference", type: "text" },
      { name: "loop_number", label: "Loop Number", type: "text" },
      { name: "calibrated_range", label: "Calibrated Range", type: "text" },
      { name: "set_point", label: "Set Point(s)", type: "text" },
      { name: "power_source", label: "Power Source", type: "text" },
      { name: "process_connection", label: "Process Connection", type: "text" },
      {
        name: "associated_equipment_id",
        label: "Associated Equipment",
        type: "fk",
        fkChapter: "project-equipment",
      },
      {
        name: "cable_id",
        label: "Cable",
        type: "fk",
        fkChapter: "project-cables",
      },
      {
        name: "plc_panel_id",
        label: "PLC Panel",
        type: "fk",
        fkChapter: "project-control-panels",
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
      // local permanent attributes (custom / one-off path)
      { name: "local_manufacturer", label: "Manufacturer", type: "text", local: true },
      {
        name: "local_instrument_type",
        label: "Instrument Type",
        type: "enum",
        options: ENUMS.InstrumentType,
        local: true,
      },
      { name: "local_model", label: "Model", type: "text", local: true },
      { name: "local_signal_type", label: "Signal Type", type: "text", local: true },
      { name: "local_accuracy", label: "Accuracy", type: "text", local: true },
    ],
  },
  {
    key: "project-io-list",
    title: "I/O List",
    group: "project",
    projectScoped: true,
    fkLabelField: "io_tag",
    merge: {
      catalogChapter: "catalog-io-modules",
      catalogFkField: "catalog_io_module_id",
      catalogLabelFields: ["module_model", "io_type"],
      primaryLocalField: "local_io_module_model",
    },
    gridFields: ["io_tag", "io_type", "plc_panel_id", "plc_address", "__source__"],
    fields: [
      { name: "io_tag", label: "Tag", type: "text" },
      {
        name: "io_type",
        label: "I/O Type / Signal",
        type: "enum",
        required: true,
        options: ENUMS.IOType,
      },
      {
        name: "project_instrument_id",
        label: "Instrument",
        type: "fk",
        fkChapter: "project-instruments",
      },
      {
        name: "project_panel_component_id",
        label: "Device (Panel Component)",
        type: "fk",
        fkChapter: "project-panel-components",
      },
      {
        name: "plc_panel_id",
        label: "PLC Panel",
        type: "fk",
        fkChapter: "project-control-panels",
      },
      { name: "rack", label: "Rack", type: "text" },
      { name: "slot", label: "Slot", type: "text" },
      { name: "channel", label: "Channel", type: "text" },
      { name: "plc_address", label: "PLC Address (combined)", type: "text" },
      { name: "signal_range", label: "Signal Range", type: "text" },
      { name: "fail_state", label: "Fail State", type: "text" },
      {
        name: "alarm_priority",
        label: "Alarm Priority",
        type: "enum",
        options: ENUMS.AlarmPriority,
      },
      { name: "scada_tag", label: "SCADA Tag", type: "text" },
      {
        name: "cable_id",
        label: "Cable",
        type: "fk",
        fkChapter: "project-cables",
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
      // local permanent attribute (custom / one-off path)
      {
        name: "local_io_module_model",
        label: "I/O Module Model",
        type: "text",
        local: true,
      },
    ],
  },
  {
    key: "project-terminal-blocks",
    title: "Terminal Blocks",
    group: "project",
    projectScoped: true,
    fkLabelField: "terminal_number",
    gridFields: [
      "terminal_strip",
      "terminal_number",
      "control_panel_id",
      "wire_number",
      "device_tag",
    ],
    fields: [
      {
        name: "control_panel_id",
        label: "Panel",
        type: "fk",
        fkChapter: "project-control-panels",
      },
      { name: "terminal_strip", label: "Terminal Strip", type: "text", required: true },
      { name: "terminal_number", label: "Terminal Number", type: "text", required: true },
      { name: "wire_number", label: "Wire Number", type: "text" },
      {
        name: "cable_id",
        label: "Cable",
        type: "fk",
        fkChapter: "project-cables",
      },
      { name: "conductor_core", label: "Conductor / Core", type: "text" },
      { name: "device_tag", label: "Device Tag", type: "text" },
      { name: "signal_description", label: "Signal Description", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-terminations",
    title: "Terminations",
    group: "project",
    projectScoped: true,
    fkLabelField: "device_tag",
    gridFields: ["cable_id", "cable_end", "termination_type", "equipment_id", "device_tag"],
    fields: [
      {
        name: "cable_id",
        label: "Cable",
        type: "fk",
        fkChapter: "project-cables",
        required: true,
      },
      {
        name: "cable_end",
        label: "Cable End",
        type: "enum",
        options: ENUMS.CableEnd,
      },
      { name: "conductor_core", label: "Conductor / Core", type: "text" },
      {
        name: "termination_type",
        label: "Termination Type",
        type: "enum",
        options: ENUMS.TerminationType,
      },
      {
        name: "equipment_id",
        label: "Equipment",
        type: "fk",
        fkChapter: "project-equipment",
      },
      {
        name: "terminal_block_id",
        label: "Terminal Block",
        type: "fk",
        fkChapter: "project-terminal-blocks",
      },
      { name: "device_tag", label: "Device Tag", type: "text" },
      { name: "drawing_reference", label: "Drawing Reference", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-network-devices",
    title: "Network Devices",
    group: "project",
    projectScoped: true,
    fkLabelField: "device_tag",
    gridFields: ["device_tag", "device_type", "ip_address", "protocol", "location_id"],
    fields: [
      { name: "device_tag", label: "Device Tag", type: "text", required: true },
      {
        name: "device_type",
        label: "Device Type",
        type: "enum",
        options: ENUMS.NetworkDeviceType,
      },
      { name: "manufacturer", label: "Manufacturer", type: "text" },
      { name: "model", label: "Model", type: "text" },
      { name: "ip_address", label: "IP Address", type: "text" },
      { name: "subnet_mask", label: "Subnet Mask", type: "text" },
      {
        name: "protocol",
        label: "Protocol",
        type: "enum",
        options: ENUMS.NetworkProtocol,
      },
      { name: "port_count", label: "Port Count", type: "number" },
      {
        name: "location_id",
        label: "Location",
        type: "fk",
        fkChapter: "project-locations",
      },
      {
        name: "control_panel_id",
        label: "Control Panel",
        type: "fk",
        fkChapter: "project-control-panels",
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-drawings",
    title: "Drawings",
    group: "project",
    projectScoped: true,
    fkLabelField: "drawing_number",
    gridFields: ["drawing_number", "title", "drawing_type", "revision", "status"],
    fields: [
      { name: "drawing_number", label: "Drawing Number", type: "text", required: true },
      { name: "title", label: "Title", type: "text" },
      {
        name: "drawing_type",
        label: "Drawing Type",
        type: "enum",
        options: ENUMS.DrawingType,
      },
      { name: "revision", label: "Revision", type: "text" },
      {
        name: "status",
        label: "Status",
        type: "enum",
        options: ENUMS.DrawingStatus,
      },
      { name: "discipline", label: "Discipline", type: "text" },
      { name: "sheet_size", label: "Sheet Size", type: "text" },
      { name: "scale", label: "Scale", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-calculations",
    title: "Calculations",
    group: "project",
    projectScoped: true,
    fkLabelField: "calc_number",
    gridFields: ["calc_number", "title", "calc_type", "revision", "status"],
    fields: [
      { name: "calc_number", label: "Calculation Number", type: "text", required: true },
      { name: "title", label: "Title", type: "text" },
      {
        name: "calc_type",
        label: "Calculation Type",
        type: "enum",
        options: ENUMS.CalcType,
      },
      { name: "revision", label: "Revision", type: "text" },
      {
        name: "status",
        label: "Status",
        type: "enum",
        options: ENUMS.CalcStatus,
      },
      { name: "result_summary", label: "Result Summary", type: "text" },
      { name: "performed_by", label: "Performed By", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  {
    key: "project-qaqc-checks",
    title: "QA/QC Checks",
    group: "project",
    projectScoped: true,
    fkLabelField: "check_item",
    gridFields: ["check_item", "category", "severity", "status", "related_reference"],
    fields: [
      { name: "check_item", label: "Check Item", type: "text", required: true },
      {
        name: "category",
        label: "Category",
        type: "enum",
        options: ENUMS.QAQCCategory,
      },
      {
        name: "severity",
        label: "Severity",
        type: "enum",
        options: ENUMS.QAQCSeverity,
      },
      {
        name: "status",
        label: "Status",
        type: "enum",
        required: true,
        options: ENUMS.QAQCStatus,
      },
      { name: "related_reference", label: "Related Reference", type: "text" },
      { name: "finding", label: "Finding", type: "textarea" },
      { name: "resolution", label: "Resolution", type: "textarea" },
      { name: "checked_by", label: "Checked By", type: "text" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
];

// ---------------------------------------------------------------------------
// cat_* catalog chapters (49 simple code/name tables)
// ---------------------------------------------------------------------------

function catChapter(key: string, title: string): ChapterDef {
  return {
    key,
    title,
    group: "catalog",
    projectScoped: false,
    fkLabelField: "name",
    gridFields: ["code", "name", "is_active"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_active", label: "Active", type: "bool" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  };
}

const CAT_CHAPTERS: ChapterDef[] = [
  {
    key: "cat-power-systems",
    title: "Power Systems",
    group: "catalog",
    projectScoped: false,
    fkLabelField: "name",
    gridFields: ["nominal_voltage", "phases", "frequency_hz", "wires", "system_config", "voltage_class", "code", "name", "is_active"],
    fields: [
      { name: "code",            label: "Code",            type: "text",   required: true },
      { name: "name",            label: "Name",            type: "text",   required: true },
      { name: "nominal_voltage", label: "Nominal Voltage", type: "text" },
      { name: "phases",          label: "Phases",          type: "number" },
      { name: "frequency_hz",    label: "Frequency (Hz)",  type: "number" },
      { name: "wires",           label: "Wires",           type: "number" },
      { name: "system_config",   label: "Configuration",   type: "enum",
        options: ["Single-Phase", "Split-Phase", "Wye", "Delta", "High-Leg Delta", "DC"] },
      { name: "voltage_class",   label: "Voltage Class",   type: "enum",
        options: ["Low Voltage", "Medium Voltage", "High Voltage", "Extra High Voltage", "Ultra High Voltage", "DC"] },
      { name: "description",     label: "Description",     type: "textarea" },
      { name: "is_active",       label: "Active",          type: "bool" },
      { name: "notes",           label: "Notes",           type: "textarea" },
    ],
  },
  catChapter("cat-voltage-classes",      "Voltage Classes"),
  catChapter("cat-grounding-types",      "Grounding Types"),
  catChapter("cat-phase-wire-configs",   "Phase/Wire Configs"),
  catChapter("cat-equipment-types",      "Equipment Types"),
  catChapter("cat-equipment-models",     "Equipment Models"),
  catChapter("cat-enclosures",           "Enclosures"),
  catChapter("cat-mounting-types",       "Mounting Types"),
  {
    key: "cat-switchgear", title: "Switchgear", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "rated_voltage", "rated_current", "sccr_rating", "phases", "is_active"],
    fields: [
      { name: "code",          label: "Code",           type: "text",   required: true },
      { name: "name",          label: "Name",           type: "text",   required: true },
      { name: "rated_voltage", label: "Voltage",        type: "text" },
      { name: "rated_current", label: "Current",        type: "text" },
      { name: "sccr_rating",   label: "SCCR",           type: "text" },
      { name: "phases",        label: "Phases",         type: "number" },
      { name: "description",   label: "Description",    type: "textarea" },
      { name: "is_active",     label: "Active",         type: "bool" },
      { name: "notes",         label: "Notes",          type: "textarea" },
    ],
  },
  {
    key: "cat-switchboards", title: "Switchboards", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "rated_voltage", "rated_current", "is_active"],
    fields: [
      { name: "code",          label: "Code",           type: "text",   required: true },
      { name: "name",          label: "Name",           type: "text",   required: true },
      { name: "rated_voltage", label: "Voltage",        type: "text" },
      { name: "rated_current", label: "Current",        type: "text" },
      { name: "description",   label: "Description",    type: "textarea" },
      { name: "is_active",     label: "Active",         type: "bool" },
      { name: "notes",         label: "Notes",          type: "textarea" },
    ],
  },
  {
    key: "cat-mccs", title: "Motor Control Centers", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "rated_voltage", "bus_rating", "is_active"],
    fields: [
      { name: "code",          label: "Code",           type: "text",   required: true },
      { name: "name",          label: "Name",           type: "text",   required: true },
      { name: "rated_voltage", label: "Voltage",        type: "text" },
      { name: "bus_rating",    label: "Bus Rating",     type: "text" },
      { name: "description",   label: "Description",    type: "textarea" },
      { name: "is_active",     label: "Active",         type: "bool" },
      { name: "notes",         label: "Notes",          type: "textarea" },
    ],
  },
  {
    key: "cat-panelboards", title: "Panelboards", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "rated_voltage", "rated_current", "poles", "is_active"],
    fields: [
      { name: "code",          label: "Code",           type: "text",   required: true },
      { name: "name",          label: "Name",           type: "text",   required: true },
      { name: "rated_voltage", label: "Voltage",        type: "text" },
      { name: "rated_current", label: "Current",        type: "text" },
      { name: "poles",         label: "Poles / Circuits", type: "number" },
      { name: "description",   label: "Description",    type: "textarea" },
      { name: "is_active",     label: "Active",         type: "bool" },
      { name: "notes",         label: "Notes",          type: "textarea" },
    ],
  },
  {
    key: "cat-transformers", title: "Transformers", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "kva_rating", "primary_voltage", "primary_current_a", "secondary_voltage", "secondary_current_a", "winding_config", "is_active"],
    fields: [
      { name: "code",               label: "Code",              type: "text",   required: true },
      { name: "name",               label: "Name",              type: "text",   required: true },
      { name: "kva_rating",         label: "kVA Rating",        type: "number" },
      { name: "primary_voltage",    label: "Primary Voltage",   type: "text" },
      { name: "primary_current_a",  label: "Primary FLA (A)",   type: "number" },
      { name: "secondary_voltage",  label: "Secondary Voltage", type: "text" },
      { name: "secondary_current_a",label: "Secondary FLA (A)", type: "number" },
      { name: "winding_config",     label: "Winding Config",    type: "text" },
      { name: "description",        label: "Description",       type: "textarea" },
      { name: "is_active",          label: "Active",            type: "bool" },
      { name: "notes",              label: "Notes",             type: "textarea" },
    ],
  },
  {
    key: "cat-ats", title: "Transfer Switches", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "rated_voltage", "rated_current", "poles", "is_active"],
    fields: [
      { name: "code",          label: "Code",           type: "text",   required: true },
      { name: "name",          label: "Name",           type: "text",   required: true },
      { name: "rated_voltage", label: "Voltage",        type: "text" },
      { name: "rated_current", label: "Current",        type: "text" },
      { name: "poles",         label: "Poles",          type: "number" },
      { name: "description",   label: "Description",    type: "textarea" },
      { name: "is_active",     label: "Active",         type: "bool" },
      { name: "notes",         label: "Notes",          type: "textarea" },
    ],
  },
  {
    key: "cat-generators", title: "Generators", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "rated_kw", "rated_kva", "rated_voltage", "fuel_type", "is_active"],
    fields: [
      { name: "code",          label: "Code",           type: "text",   required: true },
      { name: "name",          label: "Name",           type: "text",   required: true },
      { name: "rated_kw",      label: "kW Rating",      type: "number" },
      { name: "rated_kva",     label: "kVA Rating",     type: "number" },
      { name: "rated_voltage", label: "Voltage",        type: "text" },
      { name: "fuel_type",     label: "Fuel Type",      type: "enum", options: ["Diesel", "Natural Gas", "Propane", "Bi-Fuel", "Gasoline"] },
      { name: "description",   label: "Description",    type: "textarea" },
      { name: "is_active",     label: "Active",         type: "bool" },
      { name: "notes",         label: "Notes",          type: "textarea" },
    ],
  },
  {
    key: "cat-ups", title: "UPS Systems", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "rated_kva", "battery_runtime_min", "is_active"],
    fields: [
      { name: "code",                 label: "Code",              type: "text",   required: true },
      { name: "name",                 label: "Name",              type: "text",   required: true },
      { name: "rated_kva",            label: "kVA Rating",        type: "number" },
      { name: "battery_runtime_min",  label: "Battery Runtime (min)", type: "number" },
      { name: "description",          label: "Description",       type: "textarea" },
      { name: "is_active",            label: "Active",            type: "bool" },
      { name: "notes",                label: "Notes",             type: "textarea" },
    ],
  },
  catChapter("cat-breakers",             "Breakers"),
  catChapter("cat-fuses",                "Fuses"),
  catChapter("cat-relays",               "Relays"),
  catChapter("cat-overloads",            "Overloads"),
  {
    key: "cat-disconnect-switches", title: "Disconnect Switches", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "amp_rating", "voltage_rating", "fusible", "poles", "is_active"],
    fields: [
      { name: "code",          label: "Code",           type: "text",   required: true },
      { name: "name",          label: "Name",           type: "text",   required: true },
      { name: "amp_rating",    label: "Amp Rating",     type: "text" },
      { name: "voltage_rating",label: "Voltage",        type: "text" },
      { name: "fusible",       label: "Fusible",        type: "bool" },
      { name: "poles",         label: "Poles",          type: "number" },
      { name: "description",   label: "Description",    type: "textarea" },
      { name: "is_active",     label: "Active",         type: "bool" },
      { name: "notes",         label: "Notes",          type: "textarea" },
    ],
  },
  {
    key: "cat-bus-ducts", title: "Bus Duct / Busway", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "rated_voltage", "rated_current", "phases", "bus_type", "is_active"],
    fields: [
      { name: "code",          label: "Code",           type: "text",   required: true },
      { name: "name",          label: "Name",           type: "text",   required: true },
      { name: "rated_voltage", label: "Voltage",        type: "text" },
      { name: "rated_current", label: "Current (A)",    type: "number" },
      { name: "phases",        label: "Phases",         type: "number" },
      { name: "bus_type",      label: "Bus Type",       type: "enum", options: ["Feeder", "Plug-In", "Lighting"] },
      { name: "description",   label: "Description",    type: "textarea" },
      { name: "is_active",     label: "Active",         type: "bool" },
      { name: "notes",         label: "Notes",          type: "textarea" },
    ],
  },
  {
    key: "cat-meters", title: "Metering Equipment", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "meter_class", "measurement_type", "accuracy_class", "voltage_rating", "is_active"],
    fields: [
      { name: "code",             label: "Code",             type: "text",   required: true },
      { name: "name",             label: "Name",             type: "text",   required: true },
      { name: "meter_class",      label: "Meter Class",      type: "enum", options: ["Revenue", "Check", "PQ", "DC"] },
      { name: "measurement_type", label: "Measurement Type", type: "text" },
      { name: "accuracy_class",   label: "Accuracy Class",   type: "text" },
      { name: "voltage_rating",   label: "Voltage",          type: "text" },
      { name: "description",      label: "Description",      type: "textarea" },
      { name: "is_active",        label: "Active",           type: "bool" },
      { name: "notes",            label: "Notes",            type: "textarea" },
    ],
  },
  {
    key: "cat-capacitor-banks", title: "Capacitor Banks", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "voltage_rating", "kvar_rating", "phases", "connection_type", "is_active"],
    fields: [
      { name: "code",            label: "Code",            type: "text",   required: true },
      { name: "name",            label: "Name",            type: "text",   required: true },
      { name: "voltage_rating",  label: "Voltage",         type: "text" },
      { name: "kvar_rating",     label: "kVAR Rating",     type: "number" },
      { name: "phases",          label: "Phases",          type: "number" },
      { name: "connection_type", label: "Connection",      type: "enum", options: ["Wye", "Delta"] },
      { name: "description",     label: "Description",     type: "textarea" },
      { name: "is_active",       label: "Active",          type: "bool" },
      { name: "notes",           label: "Notes",           type: "textarea" },
    ],
  },
  {
    key: "cat-pdus", title: "Power Distribution Units", group: "catalog", projectScoped: false, fkLabelField: "name",
    gridFields: ["code", "name", "input_voltage", "output_voltage", "capacity_kva", "is_active"],
    fields: [
      { name: "code",           label: "Code",             type: "text",   required: true },
      { name: "name",           label: "Name",             type: "text",   required: true },
      { name: "input_voltage",  label: "Input Voltage",    type: "text" },
      { name: "output_voltage", label: "Output Voltage",   type: "text" },
      { name: "capacity_kva",   label: "Capacity (kVA)",   type: "number" },
      { name: "outlet_type",    label: "Outlet Type",      type: "text" },
      { name: "description",    label: "Description",      type: "textarea" },
      { name: "is_active",      label: "Active",           type: "bool" },
      { name: "notes",          label: "Notes",            type: "textarea" },
    ],
  },
  catChapter("cat-soft-starters",        "Soft Starters"),
  catChapter("cat-vfds",                 "VFDs"),
  catChapter("cat-conduit-types",        "Conduit Types"),
  catChapter("cat-cable-trays",          "Cable Trays"),
  {
    key: "cat-wire-types",
    title: "Wire Types",
    group: "catalog",
    projectScoped: false,
    fkLabelField: "name",
    gridFields: ["code", "name", "voltage_rating", "temperature_rating", "is_active"],
    fields: [
      { name: "code",               label: "Code",               type: "text",   required: true },
      { name: "name",               label: "Name",               type: "text",   required: true },
      { name: "voltage_rating",     label: "Voltage Rating",     type: "text" },
      { name: "temperature_rating", label: "Temp Rating",        type: "text" },
      { name: "description",        label: "Description",        type: "textarea" },
      { name: "is_active",          label: "Active",             type: "bool" },
      { name: "notes",              label: "Notes",              type: "textarea" },
    ],
  },
  catChapter("cat-cable-insulations",    "Cable Insulations"),
  catChapter("cat-conductor-materials",  "Conductor Materials"),
  catChapter("cat-instrument-models",    "Instrument Models"),
  catChapter("cat-signal-types",         "Signal Types"),
  catChapter("cat-measurement-types",    "Measurement Types"),
  catChapter("cat-process-connections",  "Process Connections"),
  catChapter("cat-plcs",                 "PLCs"),
  catChapter("cat-plc-io",               "PLC I/O"),
  catChapter("cat-scada",                "SCADA"),
  catChapter("cat-network-devices",      "Network Devices (Cat)"),
  catChapter("cat-comm-protocols",       "Comm Protocols"),
  catChapter("cat-area-types",           "Area Types"),
  catChapter("cat-room-types",           "Room Types"),
  catChapter("cat-hazardous-areas",      "Hazardous Areas"),
  catChapter("cat-environmental-ratings","Environmental Ratings"),
  catChapter("cat-drawing-types",        "Drawing Types"),
  catChapter("cat-revision-statuses",    "Revision Statuses"),
  catChapter("cat-document-types",       "Document Types"),
  catChapter("cat-submittal-statuses",   "Submittal Statuses"),
  catChapter("cat-installation-methods", "Installation Methods"),
  catChapter("cat-mounting-details",     "Mounting Details"),
  catChapter("cat-conduit-routing",      "Conduit Routing"),
  catChapter("cat-termination-types",    "Termination Types"),
];

CHAPTERS.push(...CAT_CHAPTERS);

/** Look up a chapter by its key. */
export function getChapter(key: string): ChapterDef {
  const chapter = CHAPTERS.find((c) => c.key === key);
  if (!chapter) throw new Error(`Unknown chapter: ${key}`);
  return chapter;
}

export const CATALOG_CHAPTERS = CHAPTERS.filter((c) => c.group === "catalog");
export const PROJECT_CHAPTERS = CHAPTERS.filter((c) => c.group === "project");
