"""REST routers for the Class B project tables (excluding ``projects`` itself).

The ``projects`` registry has its own hand-written router (cascade delete,
dashboard, full-export endpoints) -- see ``routers/projects.py``.

The five catalog-linked tables also receive ``/merged`` routes.
"""

from ..models.projects import (
    ProjectCable,
    ProjectCableRoute,
    ProjectCalculation,
    ProjectConduit,
    ProjectControlPanel,
    ProjectDrawing,
    ProjectEquipment,
    ProjectFeeder,
    ProjectInstrument,
    ProjectIOPoint,
    ProjectLocation,
    ProjectNetworkDevice,
    ProjectPanelCircuit,
    ProjectPanelComponent,
    ProjectQAQCCheck,
    ProjectTerminalBlock,
    ProjectTermination,
)
from ..schemas import projects as s
from .factory import make_crud_router

routers = [
    make_crud_router(
        model=ProjectLocation,
        prefix="/api/project-locations",
        label="Project location",
        create_schema=s.LocationCreate,
        read_schema=s.LocationRead,
        update_schema=s.LocationUpdate,
    ),
    make_crud_router(
        model=ProjectFeeder,
        prefix="/api/project-feeders",
        label="Feeder",
        create_schema=s.FeederCreate,
        read_schema=s.FeederRead,
        update_schema=s.FeederUpdate,
    ),
    make_crud_router(
        model=ProjectEquipment,
        prefix="/api/project-equipment",
        label="Project equipment",
        create_schema=s.ProjectEquipmentCreate,
        read_schema=s.ProjectEquipmentRead,
        update_schema=s.ProjectEquipmentUpdate,
        merged_schema=s.ProjectEquipmentMerged,
    ),
    make_crud_router(
        model=ProjectPanelCircuit,
        prefix="/api/project-panel-circuits",
        label="Panel circuit",
        create_schema=s.PanelCircuitCreate,
        read_schema=s.PanelCircuitRead,
        update_schema=s.PanelCircuitUpdate,
    ),
    make_crud_router(
        model=ProjectCable,
        prefix="/api/project-cables",
        label="Project cable",
        create_schema=s.ProjectCableCreate,
        read_schema=s.ProjectCableRead,
        update_schema=s.ProjectCableUpdate,
        merged_schema=s.ProjectCableMerged,
    ),
    make_crud_router(
        model=ProjectCableRoute,
        prefix="/api/project-cable-routes",
        label="Cable route",
        create_schema=s.CableRouteCreate,
        read_schema=s.CableRouteRead,
        update_schema=s.CableRouteUpdate,
    ),
    make_crud_router(
        model=ProjectConduit,
        prefix="/api/project-conduits",
        label="Conduit / tray",
        create_schema=s.ConduitCreate,
        read_schema=s.ConduitRead,
        update_schema=s.ConduitUpdate,
    ),
    make_crud_router(
        model=ProjectInstrument,
        prefix="/api/project-instruments",
        label="Project instrument",
        create_schema=s.ProjectInstrumentCreate,
        read_schema=s.ProjectInstrumentRead,
        update_schema=s.ProjectInstrumentUpdate,
        merged_schema=s.ProjectInstrumentMerged,
    ),
    make_crud_router(
        model=ProjectIOPoint,
        prefix="/api/project-io-list",
        label="I/O point",
        create_schema=s.IOPointCreate,
        read_schema=s.IOPointRead,
        update_schema=s.IOPointUpdate,
        merged_schema=s.IOPointMerged,
    ),
    make_crud_router(
        model=ProjectTerminalBlock,
        prefix="/api/project-terminal-blocks",
        label="Terminal block",
        create_schema=s.TerminalBlockCreate,
        read_schema=s.TerminalBlockRead,
        update_schema=s.TerminalBlockUpdate,
    ),
    make_crud_router(
        model=ProjectTermination,
        prefix="/api/project-terminations",
        label="Termination",
        create_schema=s.TerminationCreate,
        read_schema=s.TerminationRead,
        update_schema=s.TerminationUpdate,
    ),
    make_crud_router(
        model=ProjectControlPanel,
        prefix="/api/project-control-panels",
        label="Control panel",
        create_schema=s.ControlPanelCreate,
        read_schema=s.ControlPanelRead,
        update_schema=s.ControlPanelUpdate,
    ),
    make_crud_router(
        model=ProjectPanelComponent,
        prefix="/api/project-panel-components",
        label="Panel component",
        create_schema=s.PanelComponentCreate,
        read_schema=s.PanelComponentRead,
        update_schema=s.PanelComponentUpdate,
        merged_schema=s.PanelComponentMerged,
    ),
    make_crud_router(
        model=ProjectNetworkDevice,
        prefix="/api/project-network-devices",
        label="Network device",
        create_schema=s.NetworkDeviceCreate,
        read_schema=s.NetworkDeviceRead,
        update_schema=s.NetworkDeviceUpdate,
    ),
    make_crud_router(
        model=ProjectDrawing,
        prefix="/api/project-drawings",
        label="Drawing",
        create_schema=s.DrawingCreate,
        read_schema=s.DrawingRead,
        update_schema=s.DrawingUpdate,
    ),
    make_crud_router(
        model=ProjectCalculation,
        prefix="/api/project-calculations",
        label="Calculation",
        create_schema=s.CalculationCreate,
        read_schema=s.CalculationRead,
        update_schema=s.CalculationUpdate,
    ),
    make_crud_router(
        model=ProjectQAQCCheck,
        prefix="/api/project-qaqc-checks",
        label="QA/QC check",
        create_schema=s.QAQCCheckCreate,
        read_schema=s.QAQCCheckRead,
        update_schema=s.QAQCCheckUpdate,
    ),
]
